// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[locale]" | "/[locale]/[...rest]" | "/[locale]/about" | "/[locale]/blog" | "/[locale]/blog/[slug]" | "/[locale]/blog/author/[slug]" | "/[locale]/business" | "/[locale]/changelog" | "/[locale]/compare" | "/[locale]/compare/[competitor]" | "/[locale]/contact" | "/[locale]/customers" | "/[locale]/dev" | "/[locale]/docs" | "/[locale]/docs/[...slug]" | "/[locale]/dpa" | "/[locale]/help" | "/[locale]/integrations" | "/[locale]/merchant" | "/[locale]/networks" | "/[locale]/networks/[network]" | "/[locale]/pricing" | "/[locale]/privacy" | "/[locale]/products" | "/[locale]/products/api" | "/[locale]/products/checkout" | "/[locale]/products/invoicing" | "/[locale]/products/mcp" | "/[locale]/security" | "/[locale]/status" | "/[locale]/subprocessors" | "/[locale]/terms" | "/[locale]/use-cases" | "/[locale]/use-cases/[usecase]"
type AppRouteHandlerRoutes = "/[locale]/docs/raw/[...slug]" | "/[locale]/rss.xml" | "/llms-full.txt" | "/llms.txt" | "/media/[file]" | "/og" | "/og/blog/[locale]/[slug]" | "/openapi.json" | "/robots.txt" | "/rss.xml" | "/sitemap.xml" | "/sitemaps/[locale]" | "/sitemaps/[locale]/[file]"
type PageRoutes = never
type LayoutRoutes = "/[locale]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/[locale]": { "locale": string; }
  "/[locale]/[...rest]": { "locale": string; "rest": string[]; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/blog": { "locale": string; }
  "/[locale]/blog/[slug]": { "locale": string; "slug": string; }
  "/[locale]/blog/author/[slug]": { "locale": string; "slug": string; }
  "/[locale]/business": { "locale": string; }
  "/[locale]/changelog": { "locale": string; }
  "/[locale]/compare": { "locale": string; }
  "/[locale]/compare/[competitor]": { "locale": string; "competitor": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/customers": { "locale": string; }
  "/[locale]/dev": { "locale": string; }
  "/[locale]/docs": { "locale": string; }
  "/[locale]/docs/[...slug]": { "locale": string; "slug": string[]; }
  "/[locale]/docs/raw/[...slug]": { "locale": string; "slug": string[]; }
  "/[locale]/dpa": { "locale": string; }
  "/[locale]/help": { "locale": string; }
  "/[locale]/integrations": { "locale": string; }
  "/[locale]/merchant": { "locale": string; }
  "/[locale]/networks": { "locale": string; }
  "/[locale]/networks/[network]": { "locale": string; "network": string; }
  "/[locale]/pricing": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/products/api": { "locale": string; }
  "/[locale]/products/checkout": { "locale": string; }
  "/[locale]/products/invoicing": { "locale": string; }
  "/[locale]/products/mcp": { "locale": string; }
  "/[locale]/rss.xml": { "locale": string; }
  "/[locale]/security": { "locale": string; }
  "/[locale]/status": { "locale": string; }
  "/[locale]/subprocessors": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/[locale]/use-cases": { "locale": string; }
  "/[locale]/use-cases/[usecase]": { "locale": string; "usecase": string; }
  "/llms-full.txt": {}
  "/llms.txt": {}
  "/media/[file]": { "file": string; }
  "/og": {}
  "/og/blog/[locale]/[slug]": { "locale": string; "slug": string; }
  "/openapi.json": {}
  "/robots.txt": {}
  "/rss.xml": {}
  "/sitemap.xml": {}
  "/sitemaps/[locale]": { "locale": string; }
  "/sitemaps/[locale]/[file]": { "locale": string; "file": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[locale]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
