// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/[...rest]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/[...rest]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/[...rest]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/author/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog/author/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/author/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/blog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/business/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/business">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/business/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/compare/[competitor]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/compare/[competitor]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/compare/[competitor]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/compare">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/customers">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dev">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/docs/[...slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/docs/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/docs/[...slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/docs">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/dpa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/dpa">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/dpa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/help/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/help">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/help/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/merchant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/merchant">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/merchant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/networks/[network]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/networks/[network]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/networks/[network]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/networks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/networks">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/networks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/api/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/api">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/api/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/invoicing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/invoicing">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/invoicing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/mcp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products/mcp">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/mcp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/products">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/security">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/status">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/subprocessors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/subprocessors">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/subprocessors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/use-cases/[usecase]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/use-cases/[usecase]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/use-cases/[usecase]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/use-cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/use-cases">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/use-cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/docs/raw/[...slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/docs/raw/[...slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/docs/raw/[...slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/[locale]/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms-full.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms-full.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms-full.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/llms.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/llms.txt">> = Specific
  const handler = {} as typeof import("../../src/app/llms.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media/[file]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/media/[file]">> = Specific
  const handler = {} as typeof import("../../src/app/media/[file]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/og/blog/[locale]/[slug]/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og/blog/[locale]/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/og/blog/[locale]/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/og/route.tsx
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/og">> = Specific
  const handler = {} as typeof import("../../src/app/og/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/openapi.json/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/openapi.json">> = Specific
  const handler = {} as typeof import("../../src/app/openapi.json/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/robots.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/robots.txt">> = Specific
  const handler = {} as typeof import("../../src/app/robots.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rss.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/rss.xml">> = Specific
  const handler = {} as typeof import("../../src/app/rss.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemap.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap.xml">> = Specific
  const handler = {} as typeof import("../../src/app/sitemap.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemaps/[locale]/[file]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemaps/[locale]/[file]">> = Specific
  const handler = {} as typeof import("../../src/app/sitemaps/[locale]/[file]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/sitemaps/[locale]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemaps/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/sitemaps/[locale]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
